// <auto-generated />
namespace facebookProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_buy_to_transaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_buy_to_transaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201505091005538_Added_buy_to_transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
