// <auto-generated />
namespace facebookProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UsersTableChanged1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersTableChanged1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505090836400_UsersTableChanged1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
